git_protocol: ssh
glamour_style: dark
check_update: true
display_hyperlinks: true
host: gitlab.com
no_prompt: false
hosts:
    gitlab.com:
        api_host: gitlab.com
        git_protocol: ssh
        api_protocol: https
        user: Tony-Sol
