[tools]
node = "16.17.0"
python = "system"

[settings]
verbose = true
raw = true
yes = true
asdf_compat = false
trusted_config_paths = [
	'~/Projects',
]

# direnv config dump
# [global]
# disable_stdin = true
# load_dotenv = true
# strict_env = true

# [whitelist]
# prefix = [
# 	"~/.config/",
# 	"~/.local/",
# 	"~/Projects/",
# ]
