[tools]
argocd = "latest"
conftest = "latest" # or stay with opa
dive = "latest"
dockle = "latest"
hadolint = "latest"
helm = "latest"
helmfile = "latest"
helmwave = "latest"
kind = "latest"
krew = "latest"
kube-linter = "latest"
kubeconform = "latest"
kubectl = "latest"
kubent = "latest"
kubeone = "latest"
kustomize = "latest"
minikube = "latest"
opa = "latest" # or stay with conftest
regctl = "latest"
syft = "latest"
trivy = "latest"
# hashicorp
consul = "latest"
nomad = "latest"
packer = "latest"
terraform = "latest"
vault = "latest"
waypoint = "latest"
