[tools]
# mise components
fnox = "latest"
pitchfork = "latest"
usage = "latest"
# langs
go = "latest"
node = "latest"
python = "latest"
ruby = "latest"  # requires libz-dev libssl-dev libffi-dev libyaml-dev
rust = "latest"
# langs package managers
yarn = "latest"
pnpm = "latest"
pipx = "latest"
poetry = "latest"
# cli tools
act = "latest"
ast-grep = "latest"
bat = "latest"
ctop = "latest"
doggo = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
glab = "latest"
glow = "latest"
gokey = "latest"
gron = "latest"
grpcurl = "latest"
hexyl = "latest"
lazydocker = "latest"
lazygit = "latest"
lazyjournal = "latest"
lima = "latest"
mutagen = "latest"
octosql = "latest"
openbao = "latest"  # open-source hashicorp/vault
opentofu = "latest"  # open-source hashicorp/terraform
podlet = "latest"
podman = "latest"
process-compose = "latest"
ripgrep = "latest"
ripgrep-all = "latest"
tree-sitter = "latest"
ttyd = "latest"
vivid = "latest"
yq = "latest"
# container tools
argocd = "latest"
helm = "latest"
helmfile = "latest"
helmwave = "latest"
kind = "latest"
krew = "latest"
kompose = "latest"
kubectl = "latest"
kustomize = "latest"
minikube = "latest"

[tools.ansible]
version = "latest"
depends = ["pipx"]

[[tools.lua]]
version = "5.1"

[[tools.lua]]
version = "latest"

[tools.neovim]
version = "latest"
depends = ["lua@5.1", "tree-sitter"]

[tools.sing-box]
version = "latest"
system = true

[settings]
# @see https://mise.jdx.dev/configuration/settings.html#auto_install
auto_install = false
# @see https://mise.jdx.dev/configuration/settings.html#env_shell_expand
env_shell_expand = false
# @see https://mise.jdx.dev/configuration/settings.html#experimental
experimental = true
# @see https://mise.jdx.dev/configuration/settings.html#paranoid
paranoid = true
# @see https://mise.jdx.dev/configuration/settings.html#raw
raw = true
# @see https://mise.jdx.dev/configuration/settings.html#trusted_config_paths
# trust all mise configs in XDG_PROJECTS_DIR
trusted_config_paths = ["~/Projects"]

[settings.go]
# @see https://mise.jdx.dev/configuration/settings.html#go.set_gobin
# don't override GOBIN set in .zshenv
set_gobin = false

[settings.node]
# @see https://github.com/jdx/mise/discussions/5027
gpg_verify = false
