set runtimepath^="${XDG_CONFIG_HOME}/vim"
set runtimepath+="${XDG_DATA_HOME}/vim"
set runtimepath+="${XDG_CONFIG_HOME}/vim/after"

set packpath^="${XDG_DATA_HOME}/vim,${XDG_CONFIG_HOME}/vim"
set packpath+="${XDG_CONFIG_HOME}/vim/after,${XDG_DATA_HOME}/vim/after"

let g:netrw_home = "${XDG_DATA_HOME}/vim"

set backupdir="${XDG_STATE_HOME}/vim/backup" | call mkdir(&backupdir, 'p')
set directory="${XDG_STATE_HOME}/vim/swap"   | call mkdir(&directory, 'p')
set undodir="${XDG_STATE_HOME}/vim/undo"     | call mkdir(&undodir,   'p')
set viewdir="${XDG_STATE_HOME}/vim/view"     | call mkdir(&viewdir,   'p')

syntax on
set tabstop=4
set softtabstop=0
" set expandtab
set shiftwidth=4
set smarttab
set clipboard=unnamedplus
set viminfofile="${XDG_CONFIG_HOME}/vim/viminfo"
set viminfo="n${XDG_CONFIG_HOME}/vim/viminfo"
set number
set list
set relativenumber
set hlsearch
