syntax on
set tabstop=4
set softtabstop=0
" set expandtab
set shiftwidth=4
set smarttab
set clipboard=unnamedplus
set viminfofile="${XDG_CONFIG_HOME}/vim/viminfo"
set viminfo="n${XDG_CONFIG_HOME}/vim/viminfo"
set number
set list
set relativenumber
set hlsearch
