#!/bin/zsh

set -e

git_login() {
	git config --local user.name "Tony-Sol"
	git config --local user.email "tony.kent.nar.earth@gmail.com"
	git config --local user.signingkey "tony.kent.nar.earth@gmail.com"
}

git_login

exit 0
