input-field {
	monitor =
	size = 22%, 5%
	outline_thickness = 3
	inner_color = rgba(0, 0, 0, 0.0) # no fill

	outer_color = rgba(33ccffee) rgba(00ff99ee) 45deg
	check_color = rgba(00ff99ee) rgba(ff6633ee) 120deg
	fail_color = rgba(ff6633ee) rgba(ff0066ee) 40deg

	font_color = rgb(143, 143, 143)
	fade_on_empty = false
	rounding = 15

	font_family = $font
	placeholder_text = Input password...
	fail_text = $PAMFAIL

	# uncomment to use a letter instead of a dot to indicate the typed password
	# dots_text_format = *
	dots_center = true
	dots_size = 0.4
	dots_spacing = 0.3

	# uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
	# hide_input = true

	position = 0, -10%
	halign = center
	valign = center
}
