---
- name: Clone configs
  become: false
  gather_facts: true
  hosts: localhost
  connection: local
  tags:
    - configs
  vars:
    the_user: "{{ ansible_user_id }}"
  tasks:
    - name: Ensure zsh is default shell
      become: true
      user:
        name: "{{ the_user }}"
        shell: /bin/zsh

    - name: Clone configs from Github
      git:
        recursive: true
        repo: "https://github.com/Tony-Sol/.config.git"
        dest: "~/.config"
      register: repo_clone
      failed_when:
        - repo_clone.failed
        - not 'Local modifications exist in the destination' in repo_clone.msg

    - name: Remove existing configs
      file:
        path: "~/{{ item }}"
        state: absent
      loop:
        - .zshrc
        - .zprofile
        - .bashrc
        - .bash_profile
        - .profile

    - name: Link config to shell
      file:
        src: ".config/zsh/.zshenv"
        dest: "~/.zshenv"
        state: link

    - name: Find all files in ~/.config/git/commands
      find:
        paths: "~/.config/git/commands"
      register: find

    - name: Create symlinks to /usr/local/bin
      file:
        src: "{{ item.path }}"
        path: "~/.local/bin/{{ item.path | basename }}"
        state: link
      with_items: "{{ find.files }}"

    - name: Enable TouchId in terminal
      become: True
      lineinfile:
        path: "/etc/pam.d/sudo"
        line: "auth  sufficient  pam_tid.so"
        insertbefore: BOF

    - name: Enable TouchId in tmux
      become: True
      lineinfile:
        path: "/etc/pam.d/sudo"
        insertbefore: BOF
        # @todo remove hardcoded path to .so lib
        line: "auth  optional  /opt/homebrew/lib/pam/pam_reattach.so"

- name: Install everything
  become: false
  gather_facts: true
  hosts: localhost
  connection: local
  tags:
    - packages
  tasks:
    - name: Ensure brew is installed
      become: true
      stat:
        path: "{{ item }}"
      loop:
        - /opt/homebrew/bin/brew
        - /usr/local/bin/brew
      register: brew

    - name: Install brew
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when:
        - brew.results | selectattr("stat.exists") | list | length < 1

    - name: Install everything
      shell: brew bundle --file ~/.config/homebrew/Brewfile --no-lock
