---
- name: Clone configs
  become: false
  gather_facts: true
  hosts: all
  tags:
    - configs
  vars:
    the_user: "{{ ansible_user_id }}"
  tasks:
    - name: Ensure zsh is default shell
      become: true
      user:
        name: "{{ the_user }}"
        shell: /bin/zsh

    - name: Clone configs from Github
      git:
        repo: "https://github.com/Tony-Sol/.config.git"
        dest: "~"

    - name: Remove existing configs
      file:
        path: "~/{{ item }}"
        state: absent
      loop:
        - .zshenv
        - .zshrc
        - .zprofile
        - .bashrc
        - .bash_profile
        - .profile

    - name: Link config to shell
      file:
        src: "~/.config/zsh/.zshenv"
        dest: "~/.zshenv"
        state: link

- name: Install everything
  become: false
  gather_facts: true
  hosts: all
  tags:
    - packages
  tasks:
    - name: Ensure brew is installed
      become: true
      stat:
        path: "{{ item }}"
      loop:
        - /opt/homebrew/bin/brew
        - /usr/local/bin/brew
      register: brew

    - name: Install brew
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when:
        - brew.results | selectattr("stat.exists") | list | length < 1

    - name: Install everything
      shell: brew bundle --file ~/.config/homebrew/Brewfile --no-lock
