#!/usr/bin/env zsh

file=$1
width=$2
height=$3

MIME=$(file -Lb --mime-type "$file")

case "$MIME" in
	*application/x*-binary*|*application/octet-stream*)
		echo "Binary files cannot be previewed"
		;;
	*application/vnd.openxmlformats-officedocument.*)
		echo "OpenXML office document formats cannot be previewed"
		;;
	*application/x-tar*|*application/x-compressed-tar*|*application/x-*-compressed-tar*)
		tar -tvf "$file"
		;;
	*application/zip*)
		unzip -l "$file"
		;;
	*image/*)
		wezterm imgcat --height=auto --width=auto "$file" && false
		;;
	*)
		bat --color=always --paging=never --style=changes,numbers "$file" && false
		;;
esac
