# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
#
# you can get started by copying this config to ~/.config/hypr/hyprlock.conf
#

$font = JetBrains Mono Nerd
$fontBold = JetBrains Mono Nerd Bold

general {
    hide_cursor = false
}

auth {
	fingerprint {
		enabled = false
		# ready_message = Scan fingerprint to unlock
		# present_message = Scanning...
		# retry_delay = 250 # in milliseconds
	}
}

animations {
	enabled = true
	bezier = linear, 1, 1, 0, 0
	animation = fadeIn, 1, 5, linear
	animation = fadeOut, 1, 5, linear
	animation = inputFieldDots, 1, 2, linear
}

background {
	monitor =
	path = screenshot
	blur_passes = 3
}

input-field {
	size = 22%, 5%
	position = 0, -10%
	halign = center
	valign = center
	rounding = 15
	fade_on_empty = false
	outline_thickness = 3

	inner_color = rgba(0, 0, 0, 0.0) # no fill
	outer_color = rgba(33ccffee) rgba(00ff99ee) 45deg
	check_color = rgba(00ff99ee) rgba(ff6633ee) 120deg

	fail_text = $PAMFAIL
	fail_color = rgba(ff6633ee) rgba(ff0066ee) 40deg

	font_family = $font
	font_color = rgb(143, 143, 143)

	dots_center = true
	dots_size = 0.4
	dots_spacing = 0.3

}

label {
	monitor =
	text = $TIME
	font_size = 256
	font_family = $fontBold
	position = 0, -20%
	halign = center
	valign = top
}

label {
	monitor =
	text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
	font_size = 64
	font_family = $font
	position = 0, -40%
	halign = center
	valign = top
}

label {
	monitor =
	text = $LAYOUT[en,ru]
	font_size = 32
	font_family = $fontBold
	onclick = hyprctl switchxkblayout all next
	position = 10%, -10%
	halign = center
	valign = center
}
