#!/usr/bin/env zsh

local file="$1"
local mime_type mime_subtype
IFS="/" read -r mime_type mime_subtype <<< $(file --brief --dereference --mime-type "$file")

setopt extendedglob

case "$mime_type" in
	(#i)application)
		case "$mime_subtype" in
			(#i)vnd.openxmlformats-officedocument.*)
				echo 'OpenXML office document formats cannot be previewed'
				return ;;
			(#i)gzip|x-tar*|x-compressed-tar*|x-*-compressed-tar*)
				tar -tvf "$file"
				return ;;
			(#i)zip*)
				unzip -l "$file"
				return ;;
		esac
		;|
	(#i)inode)
		case "$mime_subtype" in
			directory)
				tree -CalFN "$file" | head -200
				return ;;
		esac
		;|
	(#i)text)
		case "$mime_subtype" in
			*)
				case "${file##*.}" in
					(#i)md)
						glow "$file"
						return ;;
					*)
						bat --color=always --paging=never --style=changes,numbers "$file"
						return ;;
				esac
		esac
		;|
	(#i)image)
		wezterm imgcat --no-resample --tmux-passthru=detect --height="${FZF_PREVIEW_LINES:-auto}" --width="${FZF_PREVIEW_COLUMNS:-auto}" "$file"
		;;
	*)
		echo "$file: unsupported mime-type: ${mime_type}/${mime_subtype}" >&2
		;;
esac
