#!/usr/bin/env zsh

local file="$1"
local mime_type mime_subtype
IFS="/" read -r mime_type mime_subtype <<< $(file --brief --dereference --mime-type "$file")

setopt extendedglob

case "$mime_type" in
	(#i)application)
		case "$mime_subtype" in
			(#i)vnd.openxmlformats-officedocument.*)
				echo 'OpenXML office document formats cannot be previewed' >&2
				return ;;
			(#i)gzip|x-tar*|x-compressed-tar*|x-*-compressed-tar*)
				tar -tvf "$file"
				return ;;
			(#i)zip*)
				unzip -l "$file"
				return ;;
		esac
		;|
	(#i)inode)
		case "$mime_subtype" in
			directory)
				tree -CalFN "$file" | head -200
				return ;;
		esac
		;|
	(#i)text)
		case "$mime_subtype" in
			*)
				case "${file##*.}" in
					(#i)md)
						command -v glow >/dev/null 2>&1 \
							&& glow "$file" \
							|| cat "$file"
						return ;;
					*)
						command -v bat >/dev/null 2>&1 \
							&& bat --color=always --paging=never --style=changes,numbers "$file" \
							|| cat --number "$file"
						return ;;
				esac
		esac
		;|
	(#i)image)
		command -v bat >/dev/null 2>&1 \
			&& wezterm imgcat --no-resample --tmux-passthru=detect --height="${FZF_PREVIEW_LINES:-auto}" --width="${FZF_PREVIEW_COLUMNS:-auto}" "$file" \
			|| echo 'wezterm imgcat required for image preview' >&2
		;;
	*)
		echo "$file: unsupported mime-type: ${mime_type}/${mime_subtype}" >&2
		;;
esac
