#!/bin/bash

set -e

tokenator() {
	case "${1}" in
		get)
			cat "$(dirname $0)/.vault-token"
			;;
		store)
			read -r token
			echo -n $token > "$(dirname $0)/.vault-token"
			;;
		erase)
			echo -n '' > "$(dirname $0)/.vault-token"
			;;
	esac
}

tokenator "${@}"

exit 0

