# @see https://wiki.hypr.land/Configuring/Permissions/
permissions {
	# permission = /usr/(bin|local/bin)/grim, screencopy, allow
	permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
	permission = /usr/(local/|)bin/hyprlock, screencopy, allow
	permission = /usr/(local/|)bin/hyprshot, screencopy, allow
	permission = /usr/(local/|)bin/hyprpm, plugin, allow
}
