[colors]
background = '#1E1E1E'
foreground = '#CCCCCC'
ansi       = [
	'#000000', # black
	'#CD3131', # red
	'#0DBC79', # green
	'#E5E510', # yellow
	'#2472C8', # blue
	'#BC3FBC', # magenta
	'#11A8CD', # cyan
	'#E5E5E5', # white
]
brights    = [
	'#666666', # black
	'#F14C4C', # red
	'#23D18B', # green
	'#F5F543', # yellow
	'#3B8EEA', # blue
	'#D670D6', # magenta
	'#29B8DB', # cyan
	'#E5E5E5', # white
]
