[colors]
background = '#F9F9F9'
foreground = '#020202'
ansi       = [
	'#020202', # black
	'#CD3232', # red
	'#00BC00', # green
	'#A5A900', # yellow
	'#0752A8', # blue
	'#BC05BC', # magenta
	'#0598BC', # cyan
	'#343434', # white
]
brights    = [
	'#5E5E5E', # black
	'#CD3333', # red
	'#1BCE1A', # green
	'#ADBB5B', # yellow
	'#0752A8', # blue
	'#C451CE', # magenta
	'#52A8C7', # cyan
	'#A6A3A6', # white
]
